package SPIRV.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FunctionControl extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FunctionControl() {
    super(0x4d403df5e7f84d28L, 0x822bebededfb9fefL, 0x4a02975cc3c00fd1L, "FunctionControl", "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018065");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_None_0 = new EnumerationDescriptor.MemberDescriptor("None", "0", 0x4a02975cc3c00fd2L, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018066");
  private final EnumerationDescriptor.MemberDescriptor myMember_Inline_0 = new EnumerationDescriptor.MemberDescriptor("Inline", "1", 0x4a02975cc3c00fd4L, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018068");
  private final EnumerationDescriptor.MemberDescriptor myMember_DontInline_0 = new EnumerationDescriptor.MemberDescriptor("DontInline", "2", 0x4a02975cc3c00fd8L, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018072");
  private final EnumerationDescriptor.MemberDescriptor myMember_Pure_0 = new EnumerationDescriptor.MemberDescriptor("Pure", "4", 0x4a02975cc3c00fddL, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018077");
  private final EnumerationDescriptor.MemberDescriptor myMember_Const_0 = new EnumerationDescriptor.MemberDescriptor("Const", "8", 0x4a02975cc3c00fe3L, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018083");
  private final EnumerationDescriptor.MemberDescriptor myMember_OptNoneINTEL_0 = new EnumerationDescriptor.MemberDescriptor("OptNoneINTEL", "0x10000", 0x4a02975cc3c00feaL, "r:987726a5-73cd-426e-b007-e45bfc637a4b(SPIRV.structure)/5332991333437018090");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x4d403df5e7f84d28L, 0x822bebededfb9fefL, 0x4a02975cc3c00fd1L, 0x4a02975cc3c00fd2L, 0x4a02975cc3c00fd4L, 0x4a02975cc3c00fd8L, 0x4a02975cc3c00fddL, 0x4a02975cc3c00fe3L, 0x4a02975cc3c00feaL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_None_0, myMember_Inline_0, myMember_DontInline_0, myMember_Pure_0, myMember_Const_0, myMember_OptNoneINTEL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "None":
        return myMember_None_0;
      case "Inline":
        return myMember_Inline_0;
      case "DontInline":
        return myMember_DontInline_0;
      case "Pure":
        return myMember_Pure_0;
      case "Const":
        return myMember_Const_0;
      case "OptNoneINTEL":
        return myMember_OptNoneINTEL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
