package SPIRV.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FunctionDefinition_Constraints extends BaseConstraintsDescriptor {
  public FunctionDefinition_Constraints() {
    super(CONCEPTS.FunctionDefinition$cd);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FunctionDefinition$cd = MetaAdapterFactory.getConcept(0x4d403df5e7f84d28L, 0x822bebededfb9fefL, 0x4a02975cc3b2a24dL, "SPIRV.structure.FunctionDefinition");
  }
}
