package SPIRV.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.constraints.rules.BaseRulesConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import jetbrains.mps.core.aspects.constraints.rules.Rule;
import java.util.Collections;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;

public final class FunctionDeclaration_ConstraintRules extends BaseRulesConstraintsDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x4d403df5e7f84d28L, 0x822bebededfb9fefL, 0x4a02975cc3b20b8fL, "SPIRV.structure.FunctionDeclaration");


  private static final List<Rule<?>> RULES = Collections.unmodifiableList(Arrays.<Rule<?>>asList());

  @NotNull
  @Override
  public List<Rule<?>> getDeclaredRules() {
    return RULES;
  }

  /*package*/ FunctionDeclaration_ConstraintRules() {
    super(CONCEPT);
  }
}
